#!/usr/bin/env python3
"""Fetch and self-host the display/UI/mono typefaces.

Reproducible replacement for the <link> tag to fonts.googleapis.com: downloads
only the `latin` and `latin-ext` woff2 subsets for the three families below and
writes `public/fonts/fonts.css` with local @font-face rules.

    python3 web/scripts/fetch-fonts.py

Re-run only when changing the FAMILIES list or to refresh the upstream builds.
Fonts are SIL Open Font License 1.1 — self-hosting is permitted.
"""

from __future__ import annotations

import pathlib
import re
import urllib.request

FAMILIES = [
    # (query param, local file stem)
    ("Fraunces:opsz,wght@9..144,300..700", "fraunces"),
    ("Instrument+Sans:wght@400..700", "instrument-sans"),
    ("JetBrains+Mono:wght@400..600", "jetbrains-mono"),
]
KEEP_SUBSETS = ("latin", "latin-ext")
CSS_URL = "https://fonts.googleapis.com/css2?family={}&display=swap"
UA = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36"
)

ROOT = pathlib.Path(__file__).resolve().parents[1]  # web/
OUT_DIR = ROOT / "public" / "fonts"


def fetch(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as response:  # noqa: S310
        return response.read()


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    blocks_out: list[str] = []
    downloaded = 0

    for query, stem in FAMILIES:
        css = fetch(CSS_URL.format(query)).decode("utf-8")
        # re.split with a capture group yields [pre, subset, block, subset, block, ...]
        parts = re.split(r"/\*\s*([a-z-]+)\s*\*/", css)[1:]
        for subset, block in zip(parts[::2], parts[1::2]):
            if subset not in KEEP_SUBSETS or "@font-face" not in block:
                continue
            url = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            if not url:
                continue
            source = url.group(1)
            name = f"{stem}-{subset}.woff2"
            (OUT_DIR / name).write_bytes(fetch(source))
            downloaded += 1
            blocks_out.append(
                block.strip().replace(source, f"/fonts/{name}")
            )

    css_path = OUT_DIR / "fonts.css"
    css_path.write_text(
        "/* Generated by web/scripts/fetch-fonts.py — do not edit by hand. */\n"
        + "\n".join(blocks_out)
        + "\n",
        encoding="utf-8",
    )
    total = sum(f.stat().st_size for f in OUT_DIR.glob("*.woff2"))
    print(f"{downloaded} woff2 subsets -> {OUT_DIR}")
    print(f"{css_path} ({css_path.stat().st_size} bytes)")
    print(f"total font payload: {total / 1024:.1f} KB")


if __name__ == "__main__":
    main()
